"""autogenerated by genmsg_py from Motor.msg. Do not edit."""
import roslib.message
import struct

import AER.msg

class Motor(roslib.message.Message):
  _md5sum = "465a9d69c340f3ffc464f73f8bfb6807"
  _type = "AER/Motor"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """MotorVector front
MotorVector rear

================================================================================
MSG: AER/MotorVector
float64 M0
float64 M1

"""
  __slots__ = ['front','rear']
  _slot_types = ['AER/MotorVector','AER/MotorVector']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       front,rear
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(Motor, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.front is None:
        self.front = AER.msg.MotorVector()
      if self.rear is None:
        self.rear = AER.msg.MotorVector()
    else:
      self.front = AER.msg.MotorVector()
      self.rear = AER.msg.MotorVector()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_4d.pack(_x.front.M0, _x.front.M1, _x.rear.M0, _x.rear.M1))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      if self.front is None:
        self.front = AER.msg.MotorVector()
      if self.rear is None:
        self.rear = AER.msg.MotorVector()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.front.M0, _x.front.M1, _x.rear.M0, _x.rear.M1,) = _struct_4d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_4d.pack(_x.front.M0, _x.front.M1, _x.rear.M0, _x.rear.M1))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      if self.front is None:
        self.front = AER.msg.MotorVector()
      if self.rear is None:
        self.rear = AER.msg.MotorVector()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.front.M0, _x.front.M1, _x.rear.M0, _x.rear.M1,) = _struct_4d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_4d = struct.Struct("<4d")
