"""autogenerated by genmsg_py from Sensor.msg. Do not edit."""
import roslib.message
import struct

import AER.msg

class Sensor(roslib.message.Message):
  _md5sum = "08f7e8a6fe1e6668d109a6a4d5f97003"
  _type = "AER/Sensor"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """Vector3 accelerometer
Vector3 gyroscope

================================================================================
MSG: AER/Vector3
float64 x
float64 y
float64 z

"""
  __slots__ = ['accelerometer','gyroscope']
  _slot_types = ['AER/Vector3','AER/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       accelerometer,gyroscope
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(Sensor, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.accelerometer is None:
        self.accelerometer = AER.msg.Vector3()
      if self.gyroscope is None:
        self.gyroscope = AER.msg.Vector3()
    else:
      self.accelerometer = AER.msg.Vector3()
      self.gyroscope = AER.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_6d.pack(_x.accelerometer.x, _x.accelerometer.y, _x.accelerometer.z, _x.gyroscope.x, _x.gyroscope.y, _x.gyroscope.z))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      if self.accelerometer is None:
        self.accelerometer = AER.msg.Vector3()
      if self.gyroscope is None:
        self.gyroscope = AER.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.accelerometer.x, _x.accelerometer.y, _x.accelerometer.z, _x.gyroscope.x, _x.gyroscope.y, _x.gyroscope.z,) = _struct_6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_6d.pack(_x.accelerometer.x, _x.accelerometer.y, _x.accelerometer.z, _x.gyroscope.x, _x.gyroscope.y, _x.gyroscope.z))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      if self.accelerometer is None:
        self.accelerometer = AER.msg.Vector3()
      if self.gyroscope is None:
        self.gyroscope = AER.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.accelerometer.x, _x.accelerometer.y, _x.accelerometer.z, _x.gyroscope.x, _x.gyroscope.y, _x.gyroscope.z,) = _struct_6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_6d = struct.Struct("<6d")
